### ISSUE TITLE
Complain about events that don't have final rounds

### ISSUE THREAD

**Issue by jfly** [cubing/wca-workbook-assistant#104] opened 2015-02-13 21:07 UTC
This happened with Los Lomas 2014:

![2015-02-13_836x111_laptor](https://cloud.githubusercontent.com/assets/277474/6195257/182ebfb6-b381-11e4-8f70-4d48460792e0.png)

The wca upload scripts were able to detect and fix this, but they didn't fix the corresponding uploaded scrambles (an understandable oversight, since we only added scramble uploading recently).

**Comment by jazzthief81** [comment] 2015-02-14 18:26
This is a duplicate of #68.

**Closed by jazzthief81** 2015-02-14 18:26 UTC
